name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Wait for Vercel deployment
        if: github.event_name == 'push'
        run: |
          echo "Waiting for Vercel deployment to be ready..."
          sleep 30

      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 7

      - name: Format results
        if: always()
        run: |
          echo "## Lighthouse Results" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Score |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          
          # Parse and display scores from the assertion results
          if [ -f .lighthouseci/assertion-results.json ]; then
            node -e "
              const results = require('./.lighthouseci/assertion-results.json');
              const scores = {};
              results.forEach(r => {
                if (r.auditId && r.auditId.includes('categories:')) {
                  const category = r.auditId.replace('categories:', '');
                  const score = r.actual || 0;
                  console.log('| ' + category + ' | ' + (score * 100).toFixed(0) + '% |');
                }
              });
            " >> $GITHUB_STEP_SUMMARY
          fi